// Human: Catalog of Excel functions for the Insert Function dialog.
// Agent: READ by ExcelInsertFunctionDialog; GROUPED by Excel category labels.

export type FormulaCatalogEntry = {
  name: string;
  category: string;
  description: string;
  syntax: string;
};

export const FORMULA_CATALOG: FormulaCatalogEntry[] = [
  { name: "SUM", category: "Math", description: "Adds numbers.", syntax: "SUM(number1, [number2], ...)" },
  { name: "AVERAGE", category: "Statistical", description: "Returns the average.", syntax: "AVERAGE(number1, [number2], ...)" },
  { name: "COUNT", category: "Statistical", description: "Counts numbers.", syntax: "COUNT(value1, [value2], ...)" },
  { name: "COUNTA", category: "Statistical", description: "Counts non-empty cells.", syntax: "COUNTA(value1, [value2], ...)" },
  { name: "MIN", category: "Statistical", description: "Returns the minimum.", syntax: "MIN(number1, [number2], ...)" },
  { name: "MAX", category: "Statistical", description: "Returns the maximum.", syntax: "MAX(number1, [number2], ...)" },
  { name: "MEDIAN", category: "Statistical", description: "Returns the median.", syntax: "MEDIAN(number1, [number2], ...)" },
  { name: "IF", category: "Logical", description: "Conditional value.", syntax: "IF(logical_test, value_if_true, [value_if_false])" },
  { name: "AND", category: "Logical", description: "All arguments true.", syntax: "AND(logical1, [logical2], ...)" },
  { name: "OR", category: "Logical", description: "Any argument true.", syntax: "OR(logical1, [logical2], ...)" },
  { name: "NOT", category: "Logical", description: "Reverses logic.", syntax: "NOT(logical)" },
  { name: "IFERROR", category: "Logical", description: "Value if error.", syntax: "IFERROR(value, value_if_error)" },
  { name: "IFNA", category: "Logical", description: "Value if #N/A.", syntax: "IFNA(value, value_if_na)" },
  { name: "VLOOKUP", category: "Lookup", description: "Vertical lookup.", syntax: "VLOOKUP(lookup, table, col, [range_lookup])" },
  { name: "HLOOKUP", category: "Lookup", description: "Horizontal lookup.", syntax: "HLOOKUP(lookup, table, row, [range_lookup])" },
  { name: "XLOOKUP", category: "Lookup", description: "Modern lookup.", syntax: "XLOOKUP(lookup, lookup_array, return_array)" },
  { name: "INDEX", category: "Lookup", description: "Value at index.", syntax: "INDEX(array, row, [col])" },
  { name: "MATCH", category: "Lookup", description: "Position in range.", syntax: "MATCH(lookup, lookup_array, [match_type])" },
  { name: "SUMIF", category: "Math", description: "Sum by criteria.", syntax: "SUMIF(range, criteria, [sum_range])" },
  { name: "COUNTIF", category: "Math", description: "Count by criteria.", syntax: "COUNTIF(range, criteria)" },
  { name: "SUMIFS", category: "Math", description: "Sum by multiple criteria.", syntax: "SUMIFS(sum_range, range1, criteria1, ...)" },
  { name: "COUNTIFS", category: "Math", description: "Count by multiple criteria.", syntax: "COUNTIFS(range1, criteria1, ...)" },
  { name: "FILTER", category: "Dynamic array", description: "Filter an array.", syntax: "FILTER(array, include)" },
  { name: "SORT", category: "Dynamic array", description: "Sort an array.", syntax: "SORT(array)" },
  { name: "UNIQUE", category: "Dynamic array", description: "Distinct values.", syntax: "UNIQUE(array)" },
  { name: "SEQUENCE", category: "Dynamic array", description: "Generate sequence.", syntax: "SEQUENCE(rows, [cols], [start], [step])" },
  { name: "CONCAT", category: "Text", description: "Join text.", syntax: "CONCAT(text1, [text2], ...)" },
  { name: "LEFT", category: "Text", description: "Left characters.", syntax: "LEFT(text, [num_chars])" },
  { name: "RIGHT", category: "Text", description: "Right characters.", syntax: "RIGHT(text, [num_chars])" },
  { name: "MID", category: "Text", description: "Middle characters.", syntax: "MID(text, start, num_chars)" },
  { name: "TRIM", category: "Text", description: "Trim spaces.", syntax: "TRIM(text)" },
  { name: "UPPER", category: "Text", description: "Uppercase.", syntax: "UPPER(text)" },
  { name: "LOWER", category: "Text", description: "Lowercase.", syntax: "LOWER(text)" },
  { name: "TODAY", category: "Date", description: "Today's date.", syntax: "TODAY()" },
  { name: "NOW", category: "Date", description: "Current date/time.", syntax: "NOW()" },
  { name: "DATE", category: "Date", description: "Build date serial.", syntax: "DATE(year, month, day)" },
  { name: "NPV", category: "Financial", description: "Net present value.", syntax: "NPV(rate, value1, [value2], ...)" },
  { name: "IRR", category: "Financial", description: "Internal rate of return.", syntax: "IRR(values, [guess])" },
  { name: "PMT", category: "Financial", description: "Loan payment.", syntax: "PMT(rate, nper, pv)" },
  { name: "STDEV", category: "Statistical", description: "Sample standard deviation.", syntax: "STDEV(number1, [number2], ...)" },
  { name: "TEXTJOIN", category: "Text", description: "Join text with a delimiter.", syntax: "TEXTJOIN(delimiter, ignore_empty, text1, ...)" },
  { name: "INDIRECT", category: "Lookup", description: "Reference from a text address.", syntax: "INDIRECT(ref_text)" },
  { name: "SUMPRODUCT", category: "Math", description: "Sum of products of arrays.", syntax: "SUMPRODUCT(array1, [array2], ...)" },
  { name: "XMATCH", category: "Lookup", description: "Position of an item in an array.", syntax: "XMATCH(lookup, lookup_array)" },
  { name: "TRANSPOSE", category: "Lookup", description: "Transpose a range.", syntax: "TRANSPOSE(array)" },
  { name: "LET", category: "Logical", description: "Assign names and compute.", syntax: "LET(name1, value1, ..., calculation)" },
  { name: "LAMBDA", category: "Logical", description: "Create a custom function (limited).", syntax: "LAMBDA(param, ..., calculation)" },
  { name: "SORTBY", category: "Dynamic array", description: "Sort by a key array.", syntax: "SORTBY(array, by_array)" },
  { name: "PRODUCT", category: "Math", description: "Multiply numbers.", syntax: "PRODUCT(number1, [number2], ...)" },
  { name: "SUMSQ", category: "Math", description: "Sum of squares.", syntax: "SUMSQ(number1, [number2], ...)" },
  { name: "EXACT", category: "Text", description: "Exact text match.", syntax: "EXACT(text1, text2)" },
  { name: "EDATE", category: "Date", description: "Date plus months.", syntax: "EDATE(start_date, months)" },
  { name: "EOMONTH", category: "Date", description: "End of month.", syntax: "EOMONTH(start_date, months)" },
  { name: "IFS", category: "Logical", description: "Multiple IF conditions.", syntax: "IFS(logical1, value1, ...)" },
  { name: "SWITCH", category: "Logical", description: "Match expression to values.", syntax: "SWITCH(expr, value1, result1, ..., [default])" },
  { name: "XOR", category: "Logical", description: "Exclusive OR.", syntax: "XOR(logical1, [logical2], ...)" },
  { name: "TEXTBEFORE", category: "Text", description: "Text before delimiter.", syntax: "TEXTBEFORE(text, delimiter)" },
  { name: "TEXTAFTER", category: "Text", description: "Text after delimiter.", syntax: "TEXTAFTER(text, delimiter)" },
  { name: "REPLACE", category: "Text", description: "Replace by position.", syntax: "REPLACE(old_text, start, num_chars, new_text)" },
  { name: "DOLLAR", category: "Text", description: "Format as currency text.", syntax: "DOLLAR(number, [decimals])" },
  { name: "FIXED", category: "Text", description: "Format with fixed decimals.", syntax: "FIXED(number, [decimals], [no_commas])" },
  { name: "LARGE", category: "Statistical", description: "Kth largest value.", syntax: "LARGE(array, k)" },
  { name: "SMALL", category: "Statistical", description: "Kth smallest value.", syntax: "SMALL(array, k)" },
  { name: "PERCENTILE", category: "Statistical", description: "Kth percentile.", syntax: "PERCENTILE(array, k)" },
  { name: "COUNTBLANK", category: "Statistical", description: "Count blank cells.", syntax: "COUNTBLANK(range)" },
  { name: "AVERAGEIFS", category: "Statistical", description: "Average with multiple criteria.", syntax: "AVERAGEIFS(avg_range, range1, criteria1, ...)" },
  { name: "AVERAGEIF", category: "Statistical", description: "Average with criteria.", syntax: "AVERAGEIF(range, criteria, [avg_range])" },
  { name: "SIN", category: "Math", description: "Sine of an angle (radians).", syntax: "SIN(number)" },
  { name: "COS", category: "Math", description: "Cosine of an angle (radians).", syntax: "COS(number)" },
  { name: "TAN", category: "Math", description: "Tangent of an angle (radians).", syntax: "TAN(number)" },
  { name: "DEGREES", category: "Math", description: "Convert radians to degrees.", syntax: "DEGREES(angle)" },
  { name: "RADIANS", category: "Math", description: "Convert degrees to radians.", syntax: "RADIANS(angle)" },
  { name: "FACT", category: "Math", description: "Factorial.", syntax: "FACT(number)" },
  { name: "COMBIN", category: "Math", description: "Combinations.", syntax: "COMBIN(n, k)" },
  { name: "BASE", category: "Math", description: "Convert to text in given radix.", syntax: "BASE(number, radix, [min_length])" },
  { name: "ROMAN", category: "Math", description: "Roman numeral.", syntax: "ROMAN(number)" },
  { name: "DAYS", category: "Date", description: "Days between two dates.", syntax: "DAYS(end_date, start_date)" },
  { name: "WEEKNUM", category: "Date", description: "Week number of year.", syntax: "WEEKNUM(date)" },
  { name: "WORKDAY", category: "Date", description: "Date after N workdays.", syntax: "WORKDAY(start, days)" },
  { name: "TIME", category: "Date", description: "Time serial from h/m/s.", syntax: "TIME(hour, minute, second)" },
  { name: "ISEVEN", category: "Information", description: "True if even.", syntax: "ISEVEN(number)" },
  { name: "ISODD", category: "Information", description: "True if odd.", syntax: "ISODD(number)" },
  { name: "GEOMEAN", category: "Statistical", description: "Geometric mean.", syntax: "GEOMEAN(number1, ...)" },
  { name: "MODE", category: "Statistical", description: "Most common value.", syntax: "MODE(number1, ...)" },
  { name: "QUARTILE", category: "Statistical", description: "Quartile of a data set.", syntax: "QUARTILE(array, quart)" },
  { name: "NORMSDIST", category: "Statistical", description: "Standard normal CDF.", syntax: "NORMSDIST(z)" },
  { name: "PV", category: "Financial", description: "Present value.", syntax: "PV(rate, nper, pmt, [fv])" },
  { name: "NPER", category: "Financial", description: "Number of periods.", syntax: "NPER(rate, pmt, pv, [fv])" },
  { name: "RATE", category: "Financial", description: "Interest rate per period.", syntax: "RATE(nper, pmt, pv, [fv])" },
  { name: "IPMT", category: "Financial", description: "Interest payment.", syntax: "IPMT(rate, per, nper, pv)" },
  { name: "PPMT", category: "Financial", description: "Principal payment.", syntax: "PPMT(rate, per, nper, pv)" },
  { name: "MIRR", category: "Financial", description: "Modified internal rate of return.", syntax: "MIRR(values, finance_rate, reinvest_rate)" },
  { name: "SLN", category: "Financial", description: "Straight-line depreciation.", syntax: "SLN(cost, salvage, life)" },
  { name: "LOOKUP", category: "Lookup", description: "Vector lookup.", syntax: "LOOKUP(lookup, lookup_vector, [result_vector])" },
  { name: "ADDRESS", category: "Lookup", description: "Cell address as text.", syntax: "ADDRESS(row, col, [abs_num])" },
  { name: "ROWS", category: "Lookup", description: "Number of rows in a range.", syntax: "ROWS(array)" },
  { name: "COLUMNS", category: "Lookup", description: "Number of columns in a range.", syntax: "COLUMNS(array)" },
  { name: "TOCOL", category: "Dynamic array", description: "Transform to a column.", syntax: "TOCOL(array)" },
  { name: "TOROW", category: "Dynamic array", description: "Transform to a row.", syntax: "TOROW(array)" },
  { name: "VSTACK", category: "Dynamic array", description: "Stack arrays vertically.", syntax: "VSTACK(array1, [array2], ...)" },
  { name: "HSTACK", category: "Dynamic array", description: "Stack arrays horizontally.", syntax: "HSTACK(array1, [array2], ...)" },
  { name: "BIN2DEC", category: "Engineering", description: "Binary to decimal.", syntax: "BIN2DEC(number)" },
  { name: "DEC2BIN", category: "Engineering", description: "Decimal to binary.", syntax: "DEC2BIN(number)" },
  { name: "HEX2DEC", category: "Engineering", description: "Hex to decimal.", syntax: "HEX2DEC(number)" },
  { name: "BITAND", category: "Engineering", description: "Bitwise AND.", syntax: "BITAND(number1, number2)" },
  { name: "BITOR", category: "Engineering", description: "Bitwise OR.", syntax: "BITOR(number1, number2)" },
  { name: "CEILING.MATH", category: "Math", description: "Round up to significance.", syntax: "CEILING.MATH(number, [significance])" },
  { name: "FLOOR.MATH", category: "Math", description: "Round down to significance.", syntax: "FLOOR.MATH(number, [significance])" },
  { name: "SQRTPI", category: "Math", description: "Square root of (number × π).", syntax: "SQRTPI(number)" },
  { name: "SUBTOTAL", category: "Math", description: "Aggregate with function code.", syntax: "SUBTOTAL(function_num, ref1, ...)" },
  { name: "AGGREGATE", category: "Math", description: "Aggregate with options.", syntax: "AGGREGATE(function_num, options, ref1, ...)" },
  { name: "CONVERT", category: "Engineering", description: "Convert between units.", syntax: "CONVERT(number, from_unit, to_unit)" },
];

export const FORMULA_CATEGORIES = [...new Set(FORMULA_CATALOG.map((entry) => entry.category))].sort();
